[package]
name = "nsbench"
version = "0.1.0"
authors = ["Erik Hollensbe <linux@hollensbe.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
trust-dns-resolver = ">=0"
num_cpus = ">=0"
